Repository woorepie/woorepie-admin, pull requests merged in 2025-06, with the labels that each got.

#18 [FIX] Kafka 배당금 승인 이벤트 estate_id 변수명 불일치 수정
  wooreadmin/src/main/java/com/piehouse/wooreadmin/dividend/service/DividendServiceImpl.java
  wooreadmin/src/main/java/com/piehouse/woorepie/global/kafka/dto/DividendAcceptEvent.java
Labels: bug

#23 [FEAT] Dockerfile 추가
  wooreadmin/Dockerfile
Labels: feat, ci

#25 [FIX] estateSalePrice type 변경
  wooreadmin/src/main/java/com/piehouse/wooreadmin/estate/entity/Estate.java
  wooreadmin/src/main/java/com/piehouse/wooreadmin/sale/controller/SaleController.java
  wooreadmin/src/main/java/com/piehouse/wooreadmin/sale/service/SaleService.java
  wooreadmin/src/main/java/com/piehouse/wooreadmin/sale/service/SaleServiceImpl.java
  wooreadmin/src/main/resources/templates/dashboard.html
  wooreadmin/src/main/resources/templates/disclosure.html
  wooreadmin/src/main/resources/templates/dividend.html
  wooreadmin/src/main/resources/templates/sale.html
  wooreadmin/src/main/resources/templates/subscription.html
Labels: fix
